### ISSUE TITLE
22-update-deluge: exited 1

### ISSUE THREAD

**Issue by Redsandro** [cpoppema/docker-flexget#24]
Container fails to start. Did a `stop`, `rm`, `pull` and `start`, but the error remains:

```
Traceback (most recent call last):
  File "/usr/bin/flexget", line 7, in <module>
    from flexget import main
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 11, in <module>
    from flexget import logger
  File "/usr/lib/python2.7/site-packages/flexget/logger.py", line 16, in <module>
    from flexget.utils.tools import io_encoding
  File "/usr/lib/python2.7/site-packages/flexget/utils/tools.py", line 22, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 74, in <module>
    raise RuntimeError('Requests dependency \'chardet\' must be version >= 3.0.2, < 3.1.0!')
RuntimeError: Requests dependency 'chardet' must be version >= 3.0.2, < 3.1.0!
```

Hopefully relevant part of log:

```
[...]

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-update-flexget: executing... 

[...]

Successfully installed PySocks-1.6.8
Requirement already up-to-date: chardet in /usr/lib/python2.7/site-packages

[...]

Installing collected packages: future, click, markupsafe, jinja2, werkzeug, itsdangerous, flask, flask-login, functools32, jsonschema, pyparsing, chardet, certifi, idna, urllib3, requests, six, pytz, tempora, portend, sqlalchemy, webencodings, pynzb, zxcvbn-python, colorclass, pathlib, funcsigs, tzlocal, futures, apscheduler, babelfish, pyyaml, cheroot, cherrypy, feedparser, rebulk, python-dateutil, guessit, aniso8601, flask-restful, flask-cors, flask-restplus, plumbum, rpyc, beautifulsoup4, pyrss2gen, path.py, terminaltables, html5lib, flask-compress, flexget
  Running setup.py install for future: started
    Running setup.py install for future: finished with status 'done'
  Running setup.py install for markupsafe: started
    Running setup.py install for markupsafe: finished with status 'done'
  Running setup.py install for itsdangerous: started
    Running setup.py install for itsdangerous: finished with status 'done'
  Running setup.py install for functools32: started
    Running setup.py install for functools32: finished with status 'done'
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4

[...]

Successfully installed aniso8601-1.2.1 apscheduler-3.5.0 babelfish-0.5.5 beautifulsoup4-4.6.0 certifi-2017.4.17 chardet-3.0.3 cheroot-5.5.0 cherrypy-10.2.2 click-6.7 colorclass-2.2.0 feedparser-5.2.1 flask-0.12.2 flask-compress-1.4.0 flask-cors-3.0.2 flask-login-0.4.0 flask-restful-0.3.6 flask-restplus-0.10.1 flexget-2.11.23 funcsigs-1.0.2 functools32-3.2.3.post2 future-0.16.0 futures-3.2.0 guessit-2.0.4 html5lib-0.999999999 idna-2.5 itsdangerous-0.24 jinja2-2.9.6 jsonschema-2.6.0 markupsafe-1.0 path.py-10.3.1 pathlib-1.0.1 plumbum-1.6.3 portend-1.8 pynzb-0.1.0 pyparsing-2.2.0 pyrss2gen-1.1 python-dateutil-2.6.1 pytz-2017.2 pyyaml-3.12 rebulk-0.8.2 requests-2.16.5 rpyc-3.3.0 six-1.10.0 sqlalchemy-1.1.10 tempora-1.8 terminaltables-3.1.0 tzlocal-1.4 urllib3-1.21.1 webencodings-0.5.1 werkzeug-0.12.2 zxcvbn-python-4.4.15
[cont-init.d] 20-update-flexget: exited 0.
[cont-init.d] 21-update-transmission: executing... 
[cont-init.d] 21-update-transmission: exited 0.
[cont-init.d] 22-update-deluge: executing... 

[...]

OK: 390 MiB in 168 packages
Collecting constantly
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental
  Downloading incremental-17.5.0-py2.py3-none-any.whl
Collecting service_identity
  Downloading service_identity-17.0.0-py2.py3-none-any.whl
Collecting attrs (from service_identity)
  Downloading attrs-17.4.0-py2.py3-none-any.whl
Collecting pyasn1-modules (from service_identity)
  Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
Requirement already up-to-date: pyopenssl>=0.12 in /usr/lib/python2.7/site-packages (from service_identity)
Requirement already up-to-date: pyasn1 in /usr/lib/python2.7/site-packages (from service_identity)
Requirement already up-to-date: cryptography>=2.1.4 in /usr/lib/python2.7/site-packages (from pyopenssl>=0.12->service_identity)
Collecting six>=1.5.2 (from pyopenssl>=0.12->service_identity)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting idna>=2.1 (from cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Requirement already up-to-date: asn1crypto>=0.21.0 in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
Collecting cffi>=1.7 (from cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
  Downloading cffi-1.11.4.tar.gz (436kB)
Requirement already up-to-date: enum34 in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: ipaddress in /usr/lib/python2.7/site-packages (from cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
Requirement already up-to-date: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.7->cryptography>=2.1.4->pyopenssl>=0.12->service_identity)
Installing collected packages: constantly, incremental, attrs, pyasn1-modules, service-identity, six, idna, cffi
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: idna 2.5
    Uninstalling idna-2.5:
      Successfully uninstalled idna-2.5
  Found existing installation: cffi 1.11.2
    Uninstalling cffi-1.11.2:
      Successfully uninstalled cffi-1.11.2
  Running setup.py install for cffi: started
    Running setup.py install for cffi: finished with status 'error'
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tuo6bU/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-O6T0TN-record/install-record.txt --single-version-externally-managed --compile:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    Package 'libffi', required by 'virtual:world', not found
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/error.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/verifier.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/__init__.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/model.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/lock.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/recompiler.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/api.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/cparser.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/commontypes.py -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/_embedding.h -> build/lib.linux-x86_64-2.7/cffi
    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-2.7/cffi
    running build_ext
    building '_cffi_backend' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/c
    gcc -fno-strict-aliasing -Os -fomit-frame-pointer -g -DNDEBUG -Os -fomit-frame-pointer -g -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python2.7 -c c/_cffi_backend.c -o build/temp.linux-x86_64-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cffi
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tuo6bU/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-O6T0TN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tuo6bU/cffi/
[cont-init.d] 22-update-deluge: exited 1.
[cont-init.d] 30-set-web-passwd: executing... 
[cont-init.d] 30-set-web-passwd: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Traceback (most recent call last):
  File "/usr/bin/flexget", line 7, in <module>
    from flexget import main
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 11, in <module>
    from flexget import logger
  File "/usr/lib/python2.7/site-packages/flexget/logger.py", line 16, in <module>
    from flexget.utils.tools import io_encoding
  File "/usr/lib/python2.7/site-packages/flexget/utils/tools.py", line 22, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 74, in <module>
    raise RuntimeError('Requests dependency \'chardet\' must be version >= 3.0.2, < 3.1.0!')
RuntimeError: Requests dependency 'chardet' must be version >= 3.0.2, < 3.1.0!
```

Repeat forever:

```
Traceback (most recent call last):
  File "/usr/bin/flexget", line 7, in <module>
    from flexget import main
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 11, in <module>
    from flexget import logger
  File "/usr/lib/python2.7/site-packages/flexget/logger.py", line 16, in <module>
    from flexget.utils.tools import io_encoding
  File "/usr/lib/python2.7/site-packages/flexget/utils/tools.py", line 22, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 74, in <module>
    raise RuntimeError('Requests dependency \'chardet\' must be version >= 3.0.2, < 3.1.0!')
RuntimeError: Requests dependency 'chardet' must be version >= 3.0.2, < 3.1.0!
```

**Comment by cpoppema** [comment]
Hi @Redsandro thanks for reporting this. It seems this only happens when installing the deluge plugin, I'm looking into it.

**Comment by cpoppema** [comment]
I have no old install logs around so I can't easily check what's changed (requests or deluge), but before f9a5d73 you can see in the logs that installing deluge also installs version 2.3.0 of chardet as a system package as one of its dependencies, a version that indeed doesn't meet the requirements. After updating the alpine base from 3.6 to 3.7 it now installs version 3.0.4.

Old:
```
Installing py-chardet (2.3.0-r3)
Installing py2-chardet (2.3.0-r3)
```

New:
```
Installing py-chardet (3.0.4-r0)
Installing py2-chardet (3.0.4-r0)
```

**Comment by Redsandro** [comment]
Thank you for looking into this so swiftly.

How can I try this commit? Normally I just `docker pull cpoppema/docker-flexget` and `docker run [...]`

**Comment by cpoppema** [comment]
That should work by now too. Usually, a few minutes after the master branch has a new commit, a new version is built on Docker hub - where it is being pulled from.

**Comment by Redsandro** [comment]
Thank you @cpoppema, it works. :+1:
