### ISSUE TITLE
Encoding UTF-8 problem

### ISSUE THREAD

**Issue by RicardoVelaC** [cpoppema/docker-flexget#33]
I have used this container for a months without problems. But now I've downloaded a new build and I have problems with the same configuration file.

DEBUG log show me a loop this this lines:

`2018-10-08 17:52 DEBUG    manager                       Config file /config/config.yml selected
2018-10-08 17:52 DEBUG    manager                       sys.defaultencoding: ascii
2018-10-08 17:52 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2018-10-08 17:52 DEBUG    manager                       flexget detected io encoding: utf-8
2018-10-08 17:52 DEBUG    manager                       os.path.supports_unicode_filenames: False
2018-10-08 17:52 DEBUG    manager                       Sending command to running FlexGet process: [u'-c', u'/config/config.yml', u'--loglevel', u'debug', u'daemon', u'start', u'--autoreload-config']
`

**Comment by cpoppema** [comment]
Hi @RicardoVelaC, if I look at the logs on my system I see the same output.

```
2018-10-09 16:09 DEBUG    manager                       Config file /config/config.yml selected
2018-10-09 16:09 DEBUG    manager                       sys.defaultencoding: ascii
2018-10-09 16:09 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2018-10-09 16:09 DEBUG    manager                       flexget detected io encoding: utf-8
2018-10-09 16:09 DEBUG    manager                       os.path.supports_unicode_filenames: False
```

What problems are you actually experiencing ?

**Comment by RicardoVelaC** [comment]
I'm running it on a Synology NAS with docker package, this is the docker's log, it's a loop Flexget never starts and CPU of Synology was so hight

`There is a FlexGet process already running for this config, sending execution there.
2018-10-09 17:29 DEBUG    manager                       Sending command to running FlexGet process: [u'-c', u'/config/config.yml', u'--loglevel', u'debug', u'daemon', u'start', u'--autoreload-config']
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 42, in main
    manager.start()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 309, in start
    client = IPCClient(ipc_info['port'], ipc_info['password'])
  File "/usr/lib/python2.7/site-packages/flexget/ipc.py", line 158, in __init__
    channel = rpyc.Channel(rpyc.SocketStream.connect('127.0.0.1', port))
  File "/usr/lib/python2.7/site-packages/rpyc/core/stream.py", line 132, in connect
    return cls(cls._connect(host, port, **kwargs))
  File "/usr/lib/python2.7/site-packages/rpyc/core/stream.py", line 102, in _connect
    s.connect(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refuse`

**Comment by cpoppema** [comment]
Unfortunately I'm not familiar with Synology nor do I have one available to play around with.

Can you please try to start it with minimum configuration? See for example: https://github.com/cpoppema/docker-flexget/blob/master/sample_config.yml

If that doesn't work - if possible - can you reboot the Synology and try again?

If that's still not good enough, can you show me more about how you have the docker container configured?

**Comment by RicardoVelaC** [comment]
Synology uses Docker CE 17.05.0-0394

I try with some scenarios, with a clean install like README.md there's no problem. Works OK.

When I change for my "db-config.sqlite" and "config.yml" (both were creates with older version of your docker image) Flexget doesn't work.

Ok, this point I try with another FlexGet image with my config and DB and works perfect. But the others containers doesn't have auto-updates. This is the reason why I want to use yours.

PD: For several months I have used your container, but I re-download it for try to add the TZ ENV

**Comment by RicardoVelaC** [comment]
Ok, was my fault.
The problem was PGID and PUID at first versions of container wasn't necessary and now if necessary.
Logs show "db-config.sqlite" as RO, setting-up my PGID and PUID works ok.
