### ISSUE TITLE
Wrong Python version ?

### ISSUE THREAD

**Issue by Biosha** [cpoppema/docker-flexget#43]
Hi, 

I'm having issues installing your docker. It seems the python's version is a problem ?

There are my logs :
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 47, in main
    self.initialize()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 251, in initialize
2019-05-18 15:43 DEBUG    manager                       Config file /config/config.yml selected
2019-05-18 15:43 DEBUG    manager                       sys.defaultencoding: ascii
2019-05-18 15:43 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2019-05-18 15:43 DEBUG    manager                       flexget detected io encoding: utf-8
2019-05-18 15:43 DEBUG    manager                       os.path.supports_unicode_filenames: False
2019-05-18 15:43 DEBUG    plugin                        Trying to load plugins from: [u'/config/plugins', '/usr/lib/python2.7/site-packages/flexget/plugins']
2019-05-18 15:43 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2019-05-18 15:43 DEBUG    plugin                        Trying to load components from: [u'/config/components', '/usr/lib/python2.7/site-packages/flexget/components']
2019-05-18 15:43 DEBUG    plugin                        Plugins took 2.74 seconds to load. 296 plugins in registry.
2019-05-18 15:43 DEBUG    manager                       Connecting to: sqlite:////config/db-config.sqlite
2019-05-18 15:43 CRITICAL manager                       while parsing a block mapping in "<unicode string>", line 4, column 5: - tasks: '*' ^ expected <block end>, but found '<block mapping start>' in "<unicode string>", line 5, column 7: interval: ^
```

Thanks for this docker !

**Comment by cpoppema** [comment]
Hello @Biosha, let's see. I don't really see any reason to think python is the issue here. Have you used your configuration file with a different Flexget before ? If I look at your error log, it seems there is an error in your config.yml. If you don't mind, you can share (part of) your config here so we can take a closer look.

**Comment by Biosha** [comment]
It's the first time I tried Flexget. As you said, my config.yml was wrong... I corrected it based on your sample.

Now I get this error:
```
`Traceback (most recent call last):
  File "/usr/bin/flexget", line 10, in <module>
2019-05-18 15:55 DEBUG    manager                       Config file /config/config.yml selected
2019-05-18 15:55 DEBUG    manager                       sys.defaultencoding: ascii
2019-05-18 15:55 DEBUG    manager                       sys.getfilesystemencoding: UTF-8
2019-05-18 15:55 DEBUG    manager                       flexget detected io encoding: utf-8
2019-05-18 15:55 DEBUG    manager                       os.path.supports_unicode_filenames: False
2019-05-18 15:55 DEBUG    plugin                        Trying to load plugins from: [u'/config/plugins', '/usr/lib/python2.7/site-packages/flexget/plugins']
2019-05-18 15:55 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2019-05-18 15:55 DEBUG    plugin                        Trying to load components from: [u'/config/components', '/usr/lib/python2.7/site-packages/flexget/components']
2019-05-18 15:55 DEBUG    plugin                        Plugins took 2.76 seconds to load. 296 plugins in registry.
2019-05-18 15:55 DEBUG    manager                       Connecting to: sqlite:////config/db-config.sqlite
2019-05-18 15:55 DEBUG    manager                       config_name: config
2019-05-18 15:55 DEBUG    manager                       config_base: /config
2019-05-18 15:55 DEBUG    manager                       New config data loaded.
2019-05-18 15:55 INFO     manager                       Database upgrade is required. Attempting now.
2019-05-18 15:55 DEBUG    schema                        No schema version stored for api_rottentomatoes
2019-05-18 15:55 CRITICAL schema                        A lower schema version was returned (None) from plugin api_rottentomatoes upgrade function than passed in (-1)
2019-05-18 15:55 DEBUG    manager                       Removed /config/.config-lock
Traceback (most recent call last):
  File "/usr/bin/flexget", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 47, in main
    manager.start()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 399, in start
    self.initialize()
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 263, in initialize
    fire_event('manager.upgrade', self)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 113, in fire_event
    result = event(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flexget/db_schema.py", line 180, in upgrade_wrapper
    manager.shutdown(finish_queue=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 1042, in shutdown
    raise RuntimeError('Cannot shutdown manager that was never initialized.')
RuntimeError: Cannot shutdown manager that was never initialized.
```

**Comment by Biosha** [comment]
Ok I don't get it, but I deleted the docker and recreate it and everything works.

Sorry for the inconvenience.

**Comment by cpoppema** [comment]
No worries. I'm glad you got it working!
