### ISSUE TITLE
Flexget not starting anymore: "PluginError('File %s does not exist!' % variables_file)"

### ISSUE THREAD

**Issue by Jeeaaasus** [cpoppema/docker-flexget#51]
Flexget service does not start anymore after latest commits.

Errors mentions "variables.yml" which is a file I have in the /config directory.
Here is the page on the variables plugin incase you are unfamiliar :)
https://flexget.com/Plugins/variables
```
Traceback (most recent call last):,
[services.d] done.,
[services.d] starting services,
[cont-init.d] done.,
  File "/usr/bin/flexget", line 10, in <module>,
    sys.exit(main()),
  File "/usr/lib/python3.7/site-packages/flexget/__init__.py", line 47, in main,
    manager.start(),
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 399, in start,
    self.initialize(),
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 251, in initialize,
    self.update_config(config),
    self.load_config(),
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 720, in load_config,
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 731, in update_config,
    self.config = self.validate_config(config),
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 787, in validate_config,
    config = fire_event('manager.before_config_validate', config, self),
  File "/usr/lib/python3.7/site-packages/flexget/event.py", line 113, in fire_event,
    result = event(*args, **kwargs),
  File "/usr/lib/python3.7/site-packages/flexget/event.py", line 23, in __call__,
    return self.func(*args, **kwargs),
  File "/usr/lib/python3.7/site-packages/flexget/components/variables/variables.py", line 89, in process_variables,
    variables = variables_from_file(manager.config_base, config['variables']),
  File "/usr/lib/python3.7/site-packages/flexget/components/variables/variables.py", line 42, in variables_from_file,
    raise PluginError('File %s does not exist!' % variables_file),
flexget.plugin.PluginError: File /root/.flexget/variables.yml does not exist!
```

**Comment by cpoppema** [comment]
Hi @Jeeaaasus , you are right. I believe this is caused by https://github.com/cpoppema/docker-flexget/commit/01f6263eda5fa0bf43305ef48e2d3bba35d893d0 for which I apologize. It is supposed to make running flexget commands from your host easier.

The error says `/root/.flexget/variables.yml does not exist`. This folder is now the location of the symlink to `config.yml`, so Flexget now thinks that all configuration files exist in that folder too - before this commit is actually was `/config`.

Can you do a quick test for me ? Assuming your config looks like:

```
variables: variables.yml
```

Can you change it to:

```
variables: /config/variables.yml
```

Does that help ?

**Comment by Jeeaaasus** [comment]
It's no problems dude, I appreciate the work you do!

Sure thing! and it works, it now finds the variables.yml file but it can't no longer find my custom plugin. Might be a problem unrelated to the container I'm not sure..

```
2019-08-03 01:21 CRITICAL manager                       [/tasks/Movies-Download] The key `log_filter` is not valid here. Only known plugin names are valid keys.,
Could not start manager: Did not pass schema validation.,
```

This file is located /config/plugins/log_filter.py
This worked the previous version

**Comment by cpoppema** [comment]
Unfortunately that quickfix only solves the error for variables.yml, it does indeed _not_ fix what you're seeing. I do have a fix for that, but you'll have to wait a bit until a new build is available.

**Comment by Jeeaaasus** [comment]
Okay, I'll wait patiently :)

Should I revert to
`variables: variables.yml` ?

**Comment by cpoppema** [comment]
That went actually quicker than I expected. Yes you can change it back, run `docker pull cpoppema/docker-flexget`, recreate your container and you should be good to go again :smile:

**Comment by Jeeaaasus** [comment]
Nothing changed after I re-pulled the image, I don't think the image got updated, I'm confused .. hah :D

**Comment by cpoppema** [comment]
Ooops.. that's understandable, I made a mistake and didn't actually get the new symlink right. It should be fixed this time :)

**Comment by Jeeaaasus** [comment]
Yep, that's it. All good now! 👍 Appreciate it my dude!
