### ISSUE TITLE
libtorrent dependency broken again

### ISSUE THREAD

**Issue by jawilson** [cpoppema/docker-flexget#53]
Looks like the `libtorrent` dependency from #41 is broken once again:
```
$ python3 -c 'import libtorrent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
```

When the container is starting up, I see this in the logs:
```
ERROR: unsatisfiable constraints:
  boost-python3-1.71.0-r0:
    masked in: @edge
    satisfies: world[boost-python3]
               py3-libtorrent-rasterbar-1.2.2-r0[so:libboost_python37.so.1.71.0]
```

I attempted to fix the issue by running:
`apk add --no-cache --update boost-python3@edge py3-libtorrent-rasterbar@testing`
But then I get:
```
python3 -c 'import libtorrent'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Error relocating /usr/lib/python3.7/site-packages/libtorrent.cpython-37m-x86_64-linux-gnu.so: _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEC2Ev: symbol not found
```

**Comment by cpoppema** [comment]
Hello @jawilson.

If I do a clean build I don't see this error `unsatisfiable constraints`, but I do see the same `ImportError`. 

```
# python3 -c "import libtorrent"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: Error relocating /usr/lib/python3.7/site-packages/libtorrent.cpython-37m-x86_64-linux-gnu.so: _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEC2Ev: symbol not found
```

After some researching I come across this:

```
# root@67a4ea757bcc:/# strings /usr/lib/libstdc++.so.6 | grep _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEC2E
<no output>
```

Ergo, apparently this version of libstdc++.so.6 is outdated, so can we update ? Apparently we can!

```
# apk list | grep "^gcc\|^g++\|^libstdc++" | grep installed
g++-8.3.0-r0 x86_64 {gcc} (GPL LGPL) [installed]
gcc-8.3.0-r0 x86_64 {gcc} (GPL LGPL) [installed]
libstdc++-8.3.0-r0 x86_64 {gcc} (GPL LGPL) [installed]

# apk list | grep "^gcc\|^g++\|^libstdc++" | grep upgradable
g++-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [upgradable from: g++-8.3.0-r0]
gcc-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [upgradable from: gcc-8.3.0-r0]
libstdc++-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [upgradable from: libstdc++-8.3.0-r0]
```

```
# apk add g++@edge gcc@edge
(1/6) Upgrading libstdc++@edge (8.3.0-r0 -> 9.2.0-r2)
(2/6) Upgrading libgomp@edge (8.3.0-r0 -> 9.2.0-r2)
(3/6) Upgrading libatomic@edge (8.3.0-r0 -> 9.2.0-r2)
(4/6) Installing mpfr4@edge (4.0.2-r1)
(5/6) Upgrading gcc@edge (8.3.0-r0 -> 9.2.0-r2)
(6/6) Upgrading g++@edge (8.3.0-r0 -> 9.2.0-r2)
Executing busybox-1.30.1-r2.trigger
OK: 421 MiB in 104 packages

# apk list | grep "^gcc\|^g++\|^libstdc++" | grep installed
g++-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [installed]
gcc-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [installed]
libstdc++-9.2.0-r2 x86_64 {gcc} (GPL LGPL) [installed]
```

So did it work ?

```
# strings /usr/lib/libstdc++.so.6 | grep _ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEC2E
_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEC2Ev
```

Looking good! ..

```
# python3 -c "import libtorrent"
<no output>
```

Even better! No more error!

I now install both gcc/g++ from `@edge` in the image. I have just uploaded new images, so please run `docker pull cpoppema/docker-flexget` and try again :)

**Comment by jawilson** [comment]
That did the trick, thanks! However, it's worth noting that for whatever reason `docker pull cpoppema/docker-flexget` doesn't get me the latest image, only `docker pull cpoppema/docker-flexget:amd64-latest` did. Not sure why...

**Comment by cpoppema** [comment]
Great to hear!

What you're saying is indeed unexpected. I will have to follow up on that.. I have only recently started touching multi-arch builds, so there is very likely something wrong in the way I build & push updates for containers to docker hub.

**Comment by cpoppema** [comment]
FYI: `docker pull cpoppema/docker-flexget` should now also get you the version with the latest gcc/g++ installed.
