### ISSUE TITLE
OpenSSL.SSL.WantReadError

### ISSUE THREAD

**Issue by Jeeaaasus** [cpoppema/docker-flexget#54]
Restarted one container and it got stuck.

I'm guessing urllib3 needs updating, haven't really looked into it though.

```
2019-10-31T23:10:13.959085262Z -------------------------------------
2019-10-31T23:10:13.959099365Z 
2019-10-31T23:10:13.966532688Z [cont-init.d] 10-adduser: exited 0.
2019-10-31T23:10:13.969140208Z [cont-init.d] 20-update-flexget: executing... 
2019-10-31T23:10:21.874301792Z Collecting pip
2019-10-31T23:10:24.654609068Z   Downloading https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl (1.4MB)
2019-10-31T23:10:40.014742546Z ERROR: Exception:
2019-10-31T23:10:40.014815162Z Traceback (most recent call last):
2019-10-31T23:10:40.014840089Z   File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 304, in recv_into
2019-10-31T23:10:40.014862696Z     return self.connection.recv_into(*args, **kwargs)
2019-10-31T23:10:40.014883555Z   File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1822, in recv_into
2019-10-31T23:10:40.014905372Z     self._raise_ssl_error(self._ssl, result)
2019-10-31T23:10:40.014925780Z   File "/usr/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1622, in _raise_ssl_error
2019-10-31T23:10:40.014970381Z     raise WantReadError()
2019-10-31T23:10:40.014992853Z OpenSSL.SSL.WantReadError
2019-10-31T23:10:40.015015328Z 
2019-10-31T23:10:40.015036647Z During handling of the above exception, another exception occurred:
2019-10-31T23:10:40.015057674Z 
2019-10-31T23:10:40.015077891Z Traceback (most recent call last):
2019-10-31T23:10:40.015098931Z   File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 397, in _error_catcher
2019-10-31T23:10:40.015120965Z     yield
2019-10-31T23:10:40.015143955Z   File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 479, in read
2019-10-31T23:10:40.015166024Z     data = self._fp.read(amt)
2019-10-31T23:10:40.015186951Z   File "/usr/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
2019-10-31T23:10:40.015208443Z     data = self.__fp.read(amt)
2019-10-31T23:10:40.015228865Z   File "/usr/lib/python3.7/http/client.py", line 457, in read
2019-10-31T23:10:40.015249837Z     n = self.readinto(b)
2019-10-31T23:10:40.015270932Z   File "/usr/lib/python3.7/http/client.py", line 501, in readinto
2019-10-31T23:10:40.015292636Z     n = self.fp.readinto(b)
2019-10-31T23:10:40.015313366Z   File "/usr/lib/python3.7/socket.py", line 589, in readinto
2019-10-31T23:10:40.015335215Z     return self._sock.recv_into(b)
2019-10-31T23:10:40.015355770Z   File "/usr/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 317, in recv_into
2019-10-31T23:10:40.015377894Z     raise timeout('The read operation timed out')
2019-10-31T23:10:40.015401736Z socket.timeout: The read operation timed out
```

**Comment by Jeeaaasus** [comment]
I'm really not sure where the issue lies.. sometime it doesn't give errors but then it gets stuck and doesn't progress past this point..

```
2019-11-01T15:46:44 Requirement already satisfied, skipping upgrade: pbr!=2.1.0,>=2.0.0 in /usr/lib/python3.7/site-packages (from stevedore>=1.0.0->subliminal) (5.4.3)
2019-11-01T15:46:44 fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
2019-11-01T15:47:15 fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
2019-11-01T15:47:15 fetch http://nl.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
2019-11-01T15:47:51 fetch http://nl.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
```

Might be some weird ISP related local issues.

**Comment by cpoppema** [comment]
Sorry to hear that it didn't seem to be working. I haven't gotten around to test a clean container, but if it is as you say: it works intermittently, I have to believe it's not the docker image. It might well be your ISP, but it also could've been a partial outage on pypi/alpine packages. I hope you get it to work!

**Comment by Jeeaaasus** [comment]
yeah it's working now, can't really say what the issue was, but I know it wasn't the image.

**Comment by FakeC0de** [comment]
Sorry to reply to a closed problem, but every time I'm creating the container, this same problem and log message just keep on appearing every time, I just cannot locate on the exact position of this problem. Could anyone give any clue about this problem?

**Comment by cpoppema** [comment]
Sorry to hear you're experiencing issues @JamieDummy, Can you please open a new issue and post your log output ?
