### ISSUE TITLE
SQLalchemy error: Could not parse rfc1738 URL from string ''

### ISSUE THREAD

**Issue by jorritsmit** [cpoppema/docker-flexget#78]
I get an sqlalchemy error when starting the docker. Does someone have any idea what it could be?

```
flexget          | 2020-10-20T15:00:20.148110301Z Traceback (most recent call last):
flexget          | 2020-10-20T15:00:20.148226580Z   File "/usr/bin/flexget", line 8, in <module>
flexget          | 2020-10-20T15:00:20.148312281Z     sys.exit(main())
flexget          | 2020-10-20T15:00:20.148378365Z   File "/usr/lib/python3.7/site-packages/flexget/__init__.py", line 44, in main
flexget          | 2020-10-20T15:00:20.148460540Z     manager.start()
flexget          | 2020-10-20T15:00:20.148552453Z   File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 372, in start
flexget          | 2020-10-20T15:00:20.148656879Z     self.initialize()
flexget          | 2020-10-20T15:00:20.148733523Z   File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 224, in initialize
flexget          | 2020-10-20T15:00:20.148858829Z     self.init_sqlalchemy()
flexget          | 2020-10-20T15:00:20.148949540Z   File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 809, in init_sqlalchemy
flexget          | 2020-10-20T15:00:20.149035892Z     connect_args={'check_same_thread': False, 'timeout': 10},
flexget          | 2020-10-20T15:00:20.149107557Z   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 479, in create_engine
flexget          | 2020-10-20T15:00:20.149195753Z     return strategy.create(*args, **kwargs)
flexget          | 2020-10-20T15:00:20.149266836Z   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
flexget          | 2020-10-20T15:00:20.149356776Z     u = url.make_url(name_or_url)
flexget          | 2020-10-20T15:00:20.149430103Z   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
flexget          | 2020-10-20T15:00:20.149504333Z     return _parse_rfc1738_args(name_or_url)
flexget          | 2020-10-20T15:00:20.149606996Z   File "/usr/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
flexget          | 2020-10-20T15:00:20.149808084Z     "Could not parse rfc1738 URL from string '%s'" % name
flexget          | 2020-10-20T15:00:20.149877184Z sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string ''
```

**Comment by arifkin88** [comment]
I'm seeing the same thing

**Comment by cpoppema** [comment]
Hello @jorritsmit, @arifkin88. Sorry for the late reply. Are you still experiencing this problem ? Do either of you have `database_uri` in your config.yml ?

**Comment by arifkin88** [comment]
No, it randomly went away for me.  Couldn't figure out what changed to solve it. 

FYI, I'm not using database_uri

**Comment by jorritsmit** [comment]
For me as well. I just left it on forgetting about it and it suddenly started working again. Also not using database_uri

**Comment by cpoppema** [comment]
I just started looking around to find https://discuss.flexget.com/t/could-not-parse-rfc1738-url-from-string/5290, which was a bug in Flexget. It was resolved by auto-updating to the latest version once available with a fix. Good to hear both of you no longer have any issues. :smiley:
