### ISSUE TITLE
Error after new update

### ISSUE THREAD

**Issue by shinhop** [cpoppema/docker-flexget#82]
Hi i just restarted the container and stopped working promting to me this error: 

``
AttributeError: module 'pytz' has no attribute 'BaseTzInfo'
2020-11-20 21:11:52 DEBUG    manager                       Removed /root/.flexget/.config-lock
2020-11-20 21:11:54 DEBUG    manager                       Figuring out config load paths
2020-11-20 21:11:54 DEBUG    manager                       Found config: /root/.flexget/config.yml
2020-11-20 21:11:54 DEBUG    manager                       Config file /root/.flexget/config.yml selected
2020-11-20 21:11:54 DEBUG    manager                       sys.defaultencoding: utf-8
2020-11-20 21:11:54 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2020-11-20 21:11:54 DEBUG    manager                       flexget detected io encoding: utf-8
2020-11-20 21:11:54 DEBUG    manager                       os.path.supports_unicode_filenames: False
2020-11-20 21:11:54 DEBUG    plugin                        Trying to load plugins from: ['/root/.flexget/plugins', '/usr/lib/python3.7/site-packages/flexget/plugins']
2020-11-20 21:11:56 DEBUG    plugin                        Plugin `memusage` requires plugin `ext lib `guppy`` to load.
2020-11-20 21:11:56 DEBUG    stevedore._cache                 reading /root/.cache/python-entrypoints/9fa6da98ae9978001c15385a043a015b82cb41bbefb8ef4a9bdb56788394e7e4
2020-11-20 21:11:57 DEBUG    stevedore._cache                 writing to /root/.cache/python-entrypoints/9fa6da98ae9978001c15385a043a015b82cb41bbefb8ef4a9bdb56788394e7e4
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='addic7ed', value='subliminal.providers.addic7ed:Addic7edProvider', group='subliminal.providers')
2020-11-20 21:11:57 ERROR    stevedore.extension                 Could not load 'addic7ed': unexpected indent (addic7ed.py, line 234)
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0xb6bbe618>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.7/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0xb55cb0c0>
    └ <flexget.manager.Manager object at 0xb6bc5bf0>
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 382, in start
    self.initialize()
    │    └ <function Manager.initialize at 0xb55caf60>
    └ <flexget.manager.Manager object at 0xb6bc5bf0>
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 224, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
                      │  │    │    │    └ '/root/.flexget'
                      │  │    │    └ <flexget.manager.Manager object at 0xb6bc5bf0>
                      │  │    └ <function join at 0xb6c2ca98>
                      │  └ <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
                      └ <module 'os' from '/usr/lib/python3.7/os.py'>
  File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 552, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/root/.flexget/plugins', '/usr/lib/python3.7/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0xb580e810>
  File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 470, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/usr/lib/python3.7/site-packages/flexget/plugins/output/subtitles_subliminal.py')
    │              └ 'flexget.plugins.output.subtitles_subliminal'
    └ <function _import_plugin at 0xb580e7c8>
  File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 421, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.output.subtitles_subliminal'
    └ <function import_module at 0xb6c5a930>
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.output.subtitles_subliminal'
           │          └ <function _gcd_import at 0xb6cbfed0>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/flexget/plugins/output/subtitles_subliminal.py", line 15, in <module>
    from subliminal.extensions import provider_manager
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/subliminal/__init__.py", line 11, in <module>
    from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/subliminal/core.py", line 16, in <module>
    from .extensions import provider_manager, default_providers, refiner_manager
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/subliminal/extensions.py", line 99, in <module>
    'tvsubtitles = subliminal.providers.tvsubtitles:TVsubtitlesProvider'
  File "/usr/lib/python3.7/site-packages/subliminal/extensions.py", line 30, in __init__
    super(RegistrableExtensionManager, self).__init__(namespace, **kwargs)
          │                            │              │            └ {}
          │                            │              └ 'subliminal.providers'
          │                            └ <subliminal.extensions.RegistrableExtensionManager object at 0xb3f325d0>
          └ <class 'subliminal.extensions.RegistrableExtensionManager'>
  File "/usr/lib/python3.7/site-packages/stevedore/extension.py", line 136, in __init__
    verify_requirements)
    └ False
> File "/usr/lib/python3.7/site-packages/stevedore/extension.py", line 225, in _load_plugins
    verify_requirements,
    └ False
  File "/usr/lib/python3.7/site-packages/stevedore/extension.py", line 255, in _load_one_plugin
    plugin = ep.load()
             │  └ <function EntryPoint.load at 0xb3e95270>
             └ EntryPoint(name='addic7ed', value='subliminal.providers.addic7ed:Addic7edProvider', group='subliminal.providers')
  File "/usr/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
             │             │     └ <method 'group' of 're.Match' objects>
             │             └ <re.Match object; span=(0, 46), match='subliminal.providers.addic7ed:Addic7edProvider'>
             └ <function import_module at 0xb6c5a930>
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'subliminal.providers.addic7ed'
           │          └ <function _gcd_import at 0xb6cbfed0>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/subliminal/providers/addic7ed.py", line 234
    r = self.session.get(self.server_url + 'show/%d' % show_id, params={'season': season}, timeout=10)
    ^

IndentationError: unexpected indent
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='argenteam', value='subliminal.providers.argenteam:ArgenteamProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='legendastv', value='subliminal.providers.legendastv:LegendasTVProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='opensubtitles', value='subliminal.providers.opensubtitles:OpenSubtitlesProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='podnapisi', value='subliminal.providers.podnapisi:PodnapisiProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='shooter', value='subliminal.providers.shooter:ShooterProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='thesubdb', value='subliminal.providers.thesubdb:TheSubDBProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='tvsubtitles', value='subliminal.providers.tvsubtitles:TVsubtitlesProvider', group='subliminal.providers')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint.parse('opensubtitlesvip = subliminal.providers.opensubtitles:OpenSubtitlesVipProvider')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='hash', value='subliminal.refiners.hash:refine', group='subliminal.refiners')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='metadata', value='subliminal.refiners.metadata:refine', group='subliminal.refiners')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='omdb', value='subliminal.refiners.omdb:refine', group='subliminal.refiners')
2020-11-20 21:11:57 DEBUG    stevedore.extension                 found extension EntryPoint(name='tvdb', value='subliminal.refiners.tvdb:refine', group='subliminal.refiners')
2020-11-20 21:11:58 DEBUG    plugin                        Trying to load components from: ['/root/.flexget/components', '/usr/lib/python3.7/site-packages/flexget/components']
2020-11-20 21:11:59 CRITICAL plugin                        Exception while loading plugin flexget.components.notify.notifiers.telegram
Traceback (most recent call last):

  File "/usr/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0xb6bbe618>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/usr/lib/python3.7/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0xb55cb0c0>
    └ <flexget.manager.Manager object at 0xb6bc5bf0>
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 382, in start
    self.initialize()
    │    └ <function Manager.initialize at 0xb55caf60>
    └ <flexget.manager.Manager object at 0xb6bc5bf0>
  File "/usr/lib/python3.7/site-packages/flexget/manager.py", line 224, in initialize
    extra_components=[os.path.join(self.config_base, 'components')],
                      │  │    │    │    └ '/root/.flexget'
                      │  │    │    └ <flexget.manager.Manager object at 0xb6bc5bf0>
                      │  │    └ <function join at 0xb6c2ca98>
                      │  └ <module 'posixpath' from '/usr/lib/python3.7/posixpath.py'>
                      └ <module 'os' from '/usr/lib/python3.7/os.py'>
  File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 553, in load_plugins
    _load_components_from_dirs(extra_components)
    │                          └ ['/root/.flexget/components', '/usr/lib/python3.7/site-packages/flexget/components']
    └ <function _load_components_from_dirs at 0xb580e858>
  File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 492, in _load_components_from_dirs
    _import_plugin(package_name, component_path)
    │              │             └ PosixPath('/usr/lib/python3.7/site-packages/flexget/components/notify/notifiers/telegram.py')
    │              └ 'flexget.components.notify.notifiers.telegram'
    └ <function _import_plugin at 0xb580e7c8>
> File "/usr/lib/python3.7/site-packages/flexget/plugin.py", line 421, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.components.notify.notifiers.telegram'
    └ <function import_module at 0xb6c5a930>
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.components.notify.notifiers.telegram'
           │          └ <function _gcd_import at 0xb6cbfed0>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.7/site-packages/flexget/components/notify/notifiers/telegram.py", line 12, in <module>
    import telegram
  File "/usr/lib/python3.7/site-packages/telegram/__init__.py", line 23, in <module>
    from .user import User
  File "/usr/lib/python3.7/site-packages/telegram/user.py", line 23, in <module>
    from telegram.utils.helpers import mention_html as util_mention_html
  File "/usr/lib/python3.7/site-packages/telegram/utils/helpers.py", line 93, in <module>
    reference_timestamp: float = None, tzinfo: pytz.BaseTzInfo = None) -> float:
                                               └ <module 'pytz' from '/usr/lib/python3.7/site-packages/pytz/__init__.py'>
``

**Comment by shinhop** [comment]
Sorry to bother you, this issue has been solved multiple times. Thanks for the good work my friend, your container works like a charm

**Comment by cpoppema** [comment]
@xavierpujol Good to hear you were able to get it sorted! :)
