### ISSUE TITLE
from_transmission plugin: Unhandled error in plugin from_transmission: 'Client' object has no attribute 'http_handler'

### ISSUE THREAD

**Issue by jamie--stewart** [cpoppema/docker-flexget#85]
Hello, I updated to the latest Dockerfile (after #84), and am facing a different issue to do with a task that uses the `from_transmission` plugin:

```
2020-12-28 21:53:08 CRITICAL task          remove-stale-torrents BUG: Unhandled error in plugin from_transmission: 'Client' object has no attribute 'http_handler'
Traceback (most recent call last):

  File "/usr/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    |    -> <function Thread._bootstrap_inner at 0x7fbcfa45e5f0>
    -> <Thread(task_queue, started daemon 140449519897376)>
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
    |    -> <function Thread.run at 0x7fbcfa45e3b0>
    -> <Thread(task_queue, started daemon 140449519897376)>
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    |    |        |    |        |    -> {}
    |    |        |    |        -> <Thread(task_queue, started daemon 140449519897376)>
    |    |        |    -> ()
    |    |        -> <Thread(task_queue, started daemon 140449519897376)>
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fbcf4e124
    |    -> <bound method TaskQueue.run of <flexget.task_queue.TaskQueue object at 0x7fbcf4e12490>>
    -> <Thread(task_queue, started daemon 140449519897376)>
  File "/usr/lib/python3.7/site-packages/flexget/task_queue.py", line 46, in run
    self.current_task.execute()
    |    |            -> <function Task.execute at 0x7fbcf882f710>
    |    -> <flexget.task.Task object at 0x7fbcf4840b10>
    -> <flexget.task_queue.TaskQueue object at 0x7fbcf4e12490>
  File "/usr/lib/python3.7/site-packages/flexget/task.py", line 87, in wrapper
    return func(self, *args, **kw)
           |    |      |       -> {}
           |    |      -> ()
           |    -> <flexget.task.Task object at 0x7fbcf4840b10>
           -> <function Task.execute at 0x7fbcf882f680>
  File "/usr/lib/python3.7/site-packages/flexget/task.py", line 722, in execute
    self._execute()
    |    -> <function Task._execute at 0x7fbcf882f5f0>
    -> <flexget.task.Task object at 0x7fbcf4840b10>
  File "/usr/lib/python3.7/site-packages/flexget/task.py", line 688, in _execute
    self.__run_task_phase(phase)
    |                     -> 'input'
    -> <flexget.task.Task object at 0x7fbcf4840b10>
  File "/usr/lib/python3.7/site-packages/flexget/task.py", line 514, in __run_task_phase
    response = self.__run_plugin(plugin, phase, args)
               |                 |       |      -> (<flexget.task.Task object at 0x7fbcf4840b10>, {'host': 'host.docker.internal', 'port': 9091, 'username': 'transmission', 'pa...
               |                 |       -> 'input'
               |                 -> <PluginInfo(name=from_transmission)>
               -> <flexget.task.Task object at 0x7fbcf4840b10>
> File "/usr/lib/python3.7/site-packages/flexget/task.py", line 547, in __run_plugin
    result = method(*args, **kwargs)
             |       |       -> {}
             |       -> (<flexget.task.Task object at 0x7fbcf4840b10>, {'host': 'host.docker.internal', 'port': 9091, 'username': 'transmission', 'pa...
             -> <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>
  File "/usr/lib/python3.7/site-packages/flexget/event.py", line 20, in __call__
    return self.func(*args, **kwargs)
           |    |     |       -> {}
           |    |     -> (<flexget.task.Task object at 0x7fbcf4840b10>, {'host': 'host.docker.internal', 'port': 9091, 'username': 'transmission', 'pa...
           |    -> <bound method PluginTransmissionInput.on_task_input of <flexget.plugins.clients.transmission.PluginTransmissionInput object a...
           -> <Event(name=plugin.from_transmission.input,func=on_task_input,priority=128)>
  File "/usr/lib/python3.7/site-packages/flexget/plugins/clients/transmission.py", line 186, in on_task_input
    self.client.http_handler.set_authentication(
    |    -> <transmission_rpc.client.Client object at 0x7fbcf375c990>
    -> <flexget.plugins.clients.transmission.PluginTransmissionInput object at 0x7fbcf7e58ed0>

AttributeError: 'Client' object has no attribute 'http_handler'
```

I've attached the entire log output from the container starting to the task failing. 

It's installed:
* `transmission-rpc` `3.2.2`
* `flexget` `3.1.92`

[flexget.log](https://github.com/cpoppema/docker-flexget/files/5749013/flexget.log)

Please let me know if there's somewhere else I should be filing this issue.

**Comment by cpoppema** [comment]
@jamie--stewart thank you for the detailed error trace. At a quick glance, it seems to me the new plugin handles authentication differently and the lines of code that break is because they reference something that no longer exists in the new plugin, specifically:

https://github.com/Flexget/Flexget/blob/v3.1.92/flexget/plugins/clients/transmission.py#L183-L188
```
        # Hack/Workaround for http://flexget.com/ticket/2002
        # TODO: Proper fix
        if 'username' in config and 'password' in config:
            self.client.http_handler.set_authentication(
                self.client.url, config['username'], config['password']
            )
```

Authentication has already happened, I'm not sure why it needs to happen again. Unfortunately the reason why points to a blank 410 page: http://flexget.com/ticket/2002. It is very well possible this new plugin has no need for this "workaround", so you could try removing/disabling these few lines inside the docker container. Either way you would need to create an issue on Flexget repository: https://github.com/Flexget/Flexget/issues so they can actually remove those lines in a new Flexget version or find an alternative solution to this problem.

Steps to disable these lines of code:

1- create a file disable.patch:
```
--- transmission.py.org
+++ transmission.py
@@ -182,10 +182,10 @@
 
         # Hack/Workaround for http://flexget.com/ticket/2002
         # TODO: Proper fix
-        if 'username' in config and 'password' in config:
-            self.client.http_handler.set_authentication(
-                self.client.url, config['username'], config['password']
-            )
+#        if 'username' in config and 'password' in config:
+#            self.client.http_handler.set_authentication(
+#                self.client.url, config['username'], config['password']
+#            )
 
         session = self.client.get_session()
```

2- copy it to the running container:
```
docker cp disable.patch flexget:/usr/lib/python3.7/site-packages/flexget/plugins/clients
```

3- apply the patch inside the container
```
docker exec -it flexget bash
cd /usr/lib/python3.7/site-packages/flexget/plugins/clients
patch < disable.patch
```

4- restart flexget
```
docker exec flexget killall flexget
```

**Comment by jamie--stewart** [comment]
Thanks @cpoppema, I'll try the hotfix today and raise an issue to the Flexget plugin directly 👍 

Will keep you informed

**Comment by jamie--stewart** [comment]
Hi @cpoppema I've used your patch and it's working great, thanks!

I've also added a link back to the issue on Flexget proper that's open for this.

**Comment by cpoppema** [comment]
Closing this since the issue in the official repo seems solved :+1:
