### ISSUE TITLE
Getting requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by arifkin88** [cpoppema/docker-flexget#88]
Hi @cpoppema. I've been having issues launching docker-flexget today. See the below log. I tried deleting the image and re-pulling and running, but same results. Appreciate any help you might have. Sorry if I missed this in a previous issue, but I wasn't finding anything

```
Collecting flexget
  Obtaining dependency information for flexget from https://files.pythonhosted.org/packages/fe/78/beab98bfbeecb975c3c6ab2f180d978aa3bf0ac3cd5bb9aec2334c261eb9/FlexGet-3.7.9-py3-none-any.whl.metadata
  Using cached FlexGet-3.7.9-py3-none-any.whl.metadata (12 kB)
Collecting importlib-metadata==6.1.0 (from flexget)
  Using cached importlib_metadata-6.1.0-py3-none-any.whl (21 kB)
Collecting zipp==3.11.0 (from flexget)
  Using cached zipp-3.11.0-py3-none-any.whl (6.6 kB)
Collecting backports-zoneinfo==0.2.1 (from flexget)
  Using cached backports.zoneinfo-0.2.1.tar.gz (74 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting importlib-resources==5.10.1 (from flexget)
  Using cached importlib_resources-5.10.1-py3-none-any.whl (34 kB)
Collecting pkgutil-resolve-name==1.3.10 (from flexget)
  Using cached pkgutil_resolve_name-1.3.10-py3-none-any.whl (4.7 kB)
Collecting aniso8601==9.0.1 (from flexget)
  Using cached aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)
Collecting apscheduler==3.10.1 (from flexget)
  Using cached APScheduler-3.10.1-py3-none-any.whl (59 kB)
Collecting attrs==22.1.0 (from flexget)
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting autocommand==2.2.2 (from flexget)
  Using cached autocommand-2.2.2-py3-none-any.whl (19 kB)
Collecting babelfish==0.6.0 (from flexget)
  Using cached babelfish-0.6.0-py3-none-any.whl (93 kB)
Collecting beautifulsoup4==4.11.1 (from flexget)
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting brotli==1.0.9 (from flexget)
  Using cached Brotli-1.0.9-cp37-cp37m-musllinux_1_1_x86_64.whl (3.2 MB)
Collecting certifi==2022.12.7 (from flexget)
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer==2.1.1 (from flexget)
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting cheroot==9.0.0 (from flexget)
  Using cached cheroot-9.0.0-py2.py3-none-any.whl (100 kB)
Collecting cherrypy==18.8.0 (from flexget)
  Using cached CherryPy-18.8.0-py2.py3-none-any.whl (348 kB)
Collecting click==8.1.3 (from flexget)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting colorama==0.4.6 (from flexget)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting commonmark==0.9.1 (from flexget)
  Using cached commonmark-0.9.1-py2.py3-none-any.whl (51 kB)
Collecting feedparser==6.0.10 (from flexget)
  Using cached feedparser-6.0.10-py3-none-any.whl (81 kB)
Collecting flask-compress==1.13 (from flexget)
  Using cached Flask_Compress-1.13-py3-none-any.whl (7.9 kB)
Collecting flask-cors==3.0.10 (from flexget)
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting flask-login==0.6.2 (from flexget)
  Using cached Flask_Login-0.6.2-py3-none-any.whl (17 kB)
Collecting flask-restful==0.3.9 (from flexget)
  Using cached Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)
Collecting flask-restx==1.0.3 (from flexget)
  Using cached flask_restx-1.0.3-py2.py3-none-any.whl (5.3 MB)
Collecting flask==2.2.5 (from flexget)
  Using cached Flask-2.2.5-py3-none-any.whl (101 kB)
Collecting guessit==3.5.0 (from flexget)
  Using cached guessit-3.5.0-py3-none-any.whl (167 kB)
Collecting html5lib==1.1 (from flexget)
  Using cached html5lib-1.1-py2.py3-none-any.whl (112 kB)
Collecting idna==3.4 (from flexget)
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting inflect==6.0.2 (from flexget)
  Using cached inflect-6.0.2-py3-none-any.whl (34 kB)
Collecting itsdangerous==2.1.2 (from flexget)
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting jaraco-classes==3.2.3 (from flexget)
  Using cached jaraco.classes-3.2.3-py3-none-any.whl (6.0 kB)
Collecting jaraco-collections==3.8.0 (from flexget)
  Using cached jaraco.collections-3.8.0-py3-none-any.whl (10 kB)
Collecting jaraco-context==4.2.0 (from flexget)
  Using cached jaraco.context-4.2.0-py3-none-any.whl (5.0 kB)
Collecting jaraco-functools==3.5.2 (from flexget)
  Using cached jaraco.functools-3.5.2-py3-none-any.whl (7.3 kB)
Collecting jaraco-text==3.11.0 (from flexget)
  Using cached jaraco.text-3.11.0-py3-none-any.whl (11 kB)
Collecting jinja2==3.1.2 (from flexget)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting jsonschema==4.17.3 (from flexget)
  Using cached jsonschema-4.17.3-py3-none-any.whl (90 kB)
Collecting loguru==0.6.0 (from flexget)
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting markupsafe==2.1.1 (from flexget)
  Using cached MarkupSafe-2.1.1-cp37-cp37m-musllinux_1_1_x86_64.whl (30 kB)
Collecting more-itertools==9.0.0 (from flexget)
  Using cached more_itertools-9.0.0-py3-none-any.whl (52 kB)
Collecting packaging==22.0 (from flexget)
  Using cached packaging-22.0-py3-none-any.whl (42 kB)
Collecting plumbum==1.8.0 (from flexget)
  Using cached plumbum-1.8.0-py3-none-any.whl (117 kB)
Collecting portend==3.1.0 (from flexget)
  Using cached portend-3.1.0-py3-none-any.whl (5.3 kB)
Collecting psutil==5.9.4 (from flexget)
  Using cached psutil-5.9.4.tar.gz (485 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pydantic==1.10.2 (from flexget)
  Using cached pydantic-1.10.2-cp37-cp37m-musllinux_1_1_x86_64.whl (11.9 MB)
Collecting pygments==2.13.0 (from flexget)
  Using cached Pygments-2.13.0-py3-none-any.whl (1.1 MB)
Collecting pynzb==0.1.0 (from flexget)
  Using cached pynzb-0.1.0.tar.gz (5.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyparsing==3.0.9 (from flexget)
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting pyrsistent==0.19.2 (from flexget)
  Using cached pyrsistent-0.19.2-py3-none-any.whl (57 kB)
Collecting pyrss2gen==1.1 (from flexget)
  Using cached PyRSS2Gen-1.1.tar.gz (6.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-dateutil==2.8.2 (from flexget)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz-deprecation-shim==0.1.0.post0 (from flexget)
  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)
Collecting pytz==2022.6 (from flexget)
  Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)
Collecting pyyaml==6.0 (from flexget)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 312, in <module>
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 314, in run
          self.find_sources()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
          mm.run()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-xzfjrrzy/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by cpoppema** [comment]
Hello @arifkin88, thanks for posting the console output. I have just successfully done a fresh docker pull and recreated the container from scratch without any issues regarding PyYAML. I did however notice it installed a different version for PyYAML version 6.0.1 as well as FlexGet 3.7.10 instead of PyYAML 6.0 and FlexGet 3.7.9 that I find in your log output.

Looking at upstream, FlexGet seems to have addressed this issue with version 3.7.10 by indeed bumping the pinned version for PyYAML: https://github.com/Flexget/Flexget/commit/b3251671cc9ba6fd92719842a3948d566db6c98b

So I hope a restart of the container will automatically update - if not, try to recreate your container - this should resolve your issue. :slightly_smiling_face:

**Comment by arifkin88** [comment]
Thanks @cpoppema for the quick response and investigation. You're right, it now does look like everything is working after a restart. I'm a little confused as to why it wasn't working yesterday when I restarted, but happy it's working now!

**Comment by cpoppema** [comment]
Glad to hear it's been resolved!
